// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guess-num.proto

package com.rashlight.carnival.communication.grpc.autogen;

public interface BumpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BumpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isFail = 1;</code>
   * @return The isFail.
   */
  boolean getIsFail();
}
