// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

/**
 * Protobuf type {@code BumpResponse}
 */
public final class BumpResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BumpResponse)
    BumpResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BumpResponse.newBuilder() to construct.
  private BumpResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BumpResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BumpResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_BumpResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_BumpResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rashlight.carnival.communication.grpc.autogen.BumpResponse.class, com.rashlight.carnival.communication.grpc.autogen.BumpResponse.Builder.class);
  }

  public static final int ISFAIL_FIELD_NUMBER = 1;
  private boolean isFail_ = false;
  /**
   * <code>bool isFail = 1;</code>
   * @return The isFail.
   */
  @java.lang.Override
  public boolean getIsFail() {
    return isFail_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isFail_ != false) {
      output.writeBool(1, isFail_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isFail_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isFail_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rashlight.carnival.communication.grpc.autogen.BumpResponse)) {
      return super.equals(obj);
    }
    com.rashlight.carnival.communication.grpc.autogen.BumpResponse other = (com.rashlight.carnival.communication.grpc.autogen.BumpResponse) obj;

    if (getIsFail()
        != other.getIsFail()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISFAIL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFail());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rashlight.carnival.communication.grpc.autogen.BumpResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BumpResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BumpResponse)
      com.rashlight.carnival.communication.grpc.autogen.BumpResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_BumpResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_BumpResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rashlight.carnival.communication.grpc.autogen.BumpResponse.class, com.rashlight.carnival.communication.grpc.autogen.BumpResponse.Builder.class);
    }

    // Construct using com.rashlight.carnival.communication.grpc.autogen.BumpResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isFail_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_BumpResponse_descriptor;
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.BumpResponse getDefaultInstanceForType() {
      return com.rashlight.carnival.communication.grpc.autogen.BumpResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.BumpResponse build() {
      com.rashlight.carnival.communication.grpc.autogen.BumpResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.BumpResponse buildPartial() {
      com.rashlight.carnival.communication.grpc.autogen.BumpResponse result = new com.rashlight.carnival.communication.grpc.autogen.BumpResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rashlight.carnival.communication.grpc.autogen.BumpResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isFail_ = isFail_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rashlight.carnival.communication.grpc.autogen.BumpResponse) {
        return mergeFrom((com.rashlight.carnival.communication.grpc.autogen.BumpResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rashlight.carnival.communication.grpc.autogen.BumpResponse other) {
      if (other == com.rashlight.carnival.communication.grpc.autogen.BumpResponse.getDefaultInstance()) return this;
      if (other.getIsFail() != false) {
        setIsFail(other.getIsFail());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isFail_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isFail_ ;
    /**
     * <code>bool isFail = 1;</code>
     * @return The isFail.
     */
    @java.lang.Override
    public boolean getIsFail() {
      return isFail_;
    }
    /**
     * <code>bool isFail = 1;</code>
     * @param value The isFail to set.
     * @return This builder for chaining.
     */
    public Builder setIsFail(boolean value) {

      isFail_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool isFail = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFail() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isFail_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BumpResponse)
  }

  // @@protoc_insertion_point(class_scope:BumpResponse)
  private static final com.rashlight.carnival.communication.grpc.autogen.BumpResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rashlight.carnival.communication.grpc.autogen.BumpResponse();
  }

  public static com.rashlight.carnival.communication.grpc.autogen.BumpResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BumpResponse>
      PARSER = new com.google.protobuf.AbstractParser<BumpResponse>() {
    @java.lang.Override
    public BumpResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BumpResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BumpResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rashlight.carnival.communication.grpc.autogen.BumpResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

