// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

public final class CrashMulProto {
  private CrashMulProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentMultiplierRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentMultiplierRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentMultiplierResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentMultiplierResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InitiateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InitiateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InitiateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InitiateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentBumpTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentBumpTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentBumpTimeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentBumpTimeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BumpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BumpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BumpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BumpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013crash.proto\"\035\n\033GetCurrentMultiplierReq" +
      "uest\"2\n\034GetCurrentMultiplierResponse\022\022\n\n" +
      "multiplier\030\001 \001(\001\"\021\n\017InitiateRequest\"\022\n\020I" +
      "nitiateResponse\"\033\n\031GetCurrentBumpTimeReq" +
      "uest\".\n\032GetCurrentBumpTimeResponse\022\020\n\010bu" +
      "mpTime\030\001 \001(\005\"\r\n\013BumpRequest\"\036\n\014BumpRespo" +
      "nse\022\016\n\006isFail\030\001 \001(\0102\223\002\n\017CrashMulService\022" +
      "U\n\024getCurrentMultiplier\022\034.GetCurrentMult" +
      "iplierRequest\032\035.GetCurrentMultiplierResp" +
      "onse\"\000\0221\n\010initiate\022\020.InitiateRequest\032\021.I" +
      "nitiateResponse\"\000\022%\n\004bump\022\014.BumpRequest\032" +
      "\r.BumpResponse\"\000\022O\n\022getCurrentBumpTime\022\032" +
      ".GetCurrentBumpTimeRequest\032\033.GetCurrentB" +
      "umpTimeResponse\"\000BD\n1com.rashlight.carni" +
      "val.communication.grpc.autogenB\rCrashMul" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCurrentMultiplierRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCurrentMultiplierRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentMultiplierRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetCurrentMultiplierResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCurrentMultiplierResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentMultiplierResponse_descriptor,
        new java.lang.String[] { "Multiplier", });
    internal_static_InitiateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_InitiateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InitiateRequest_descriptor,
        new java.lang.String[] { });
    internal_static_InitiateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_InitiateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InitiateResponse_descriptor,
        new java.lang.String[] { });
    internal_static_GetCurrentBumpTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetCurrentBumpTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentBumpTimeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetCurrentBumpTimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetCurrentBumpTimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentBumpTimeResponse_descriptor,
        new java.lang.String[] { "BumpTime", });
    internal_static_BumpRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_BumpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BumpRequest_descriptor,
        new java.lang.String[] { });
    internal_static_BumpResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_BumpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BumpResponse_descriptor,
        new java.lang.String[] { "IsFail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
