// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guess-num.proto

package com.rashlight.carnival.communication.grpc.autogen;

public final class CrashMulProto {
  private CrashMulProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentMultiplierRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentMultiplierRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCurrentMultiplierResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCurrentMultiplierResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InitiateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InitiateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InitiateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InitiateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BumpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BumpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BumpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BumpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017guess-num.proto\"\035\n\033GetCurrentMultiplie" +
      "rRequest\"2\n\034GetCurrentMultiplierResponse" +
      "\022\022\n\nmultiplier\030\001 \001(\001\"\021\n\017InitiateRequest\"" +
      "\022\n\020InitiateResponse\"\r\n\013BumpRequest\"\036\n\014Bu" +
      "mpResponse\022\016\n\006isFail\030\001 \001(\0102\302\001\n\017CrashMulS" +
      "ervice\022U\n\024getCurrentMultiplier\022\034.GetCurr" +
      "entMultiplierRequest\032\035.GetCurrentMultipl" +
      "ierResponse\"\000\0221\n\010initiate\022\020.InitiateRequ" +
      "est\032\021.InitiateResponse\"\000\022%\n\004bump\022\014.BumpR" +
      "equest\032\r.BumpResponse\"\000BD\n1com.rashlight" +
      ".carnival.communication.grpc.autogenB\rCr" +
      "ashMulProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCurrentMultiplierRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCurrentMultiplierRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentMultiplierRequest_descriptor,
        new String[] { });
    internal_static_GetCurrentMultiplierResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCurrentMultiplierResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCurrentMultiplierResponse_descriptor,
        new String[] { "Multiplier", });
    internal_static_InitiateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_InitiateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InitiateRequest_descriptor,
        new String[] { });
    internal_static_InitiateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_InitiateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InitiateResponse_descriptor,
        new String[] { });
    internal_static_BumpRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BumpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BumpRequest_descriptor,
        new String[] { });
    internal_static_BumpResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BumpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BumpResponse_descriptor,
        new String[] { "IsFail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
