// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

/**
 * Protobuf type {@code GetCurrentMultiplierResponse}
 */
public final class GetCurrentMultiplierResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetCurrentMultiplierResponse)
    GetCurrentMultiplierResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCurrentMultiplierResponse.newBuilder() to construct.
  private GetCurrentMultiplierResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCurrentMultiplierResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCurrentMultiplierResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_GetCurrentMultiplierResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_GetCurrentMultiplierResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.class, com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.Builder.class);
  }

  public static final int MULTIPLIER_FIELD_NUMBER = 1;
  private double multiplier_ = 0D;
  /**
   * <code>double multiplier = 1;</code>
   * @return The multiplier.
   */
  @java.lang.Override
  public double getMultiplier() {
    return multiplier_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(multiplier_) != 0) {
      output.writeDouble(1, multiplier_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(multiplier_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, multiplier_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse)) {
      return super.equals(obj);
    }
    com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse other = (com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse) obj;

    if (java.lang.Double.doubleToLongBits(getMultiplier())
        != java.lang.Double.doubleToLongBits(
            other.getMultiplier())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMultiplier()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetCurrentMultiplierResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetCurrentMultiplierResponse)
      com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_GetCurrentMultiplierResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_GetCurrentMultiplierResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.class, com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.Builder.class);
    }

    // Construct using com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      multiplier_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rashlight.carnival.communication.grpc.autogen.CrashMulProto.internal_static_GetCurrentMultiplierResponse_descriptor;
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse getDefaultInstanceForType() {
      return com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse build() {
      com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse buildPartial() {
      com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse result = new com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.multiplier_ = multiplier_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse) {
        return mergeFrom((com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse other) {
      if (other == com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse.getDefaultInstance()) return this;
      if (other.getMultiplier() != 0D) {
        setMultiplier(other.getMultiplier());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              multiplier_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double multiplier_ ;
    /**
     * <code>double multiplier = 1;</code>
     * @return The multiplier.
     */
    @java.lang.Override
    public double getMultiplier() {
      return multiplier_;
    }
    /**
     * <code>double multiplier = 1;</code>
     * @param value The multiplier to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplier(double value) {

      multiplier_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double multiplier = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiplier() {
      bitField0_ = (bitField0_ & ~0x00000001);
      multiplier_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetCurrentMultiplierResponse)
  }

  // @@protoc_insertion_point(class_scope:GetCurrentMultiplierResponse)
  private static final com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse();
  }

  public static com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCurrentMultiplierResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCurrentMultiplierResponse>() {
    @java.lang.Override
    public GetCurrentMultiplierResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCurrentMultiplierResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCurrentMultiplierResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rashlight.carnival.communication.grpc.autogen.GetCurrentMultiplierResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

