// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

public interface GetCurrentMultiplierResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCurrentMultiplierResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double multiplier = 1;</code>
   * @return The multiplier.
   */
  double getMultiplier();
}
