// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

public interface GetCurrentMultiplierRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCurrentMultiplierRequest)
    com.google.protobuf.MessageOrBuilder {
}
