// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crash.proto

package com.rashlight.carnival.communication.grpc.autogen;

public interface GetCurrentBumpTimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCurrentBumpTimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bumpTime = 1;</code>
   * @return The bumpTime.
   */
  int getBumpTime();
}
