// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guess-num.proto

package com.rashlight.carnival.communication.grpc.autogen;

public interface InitiateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitiateRequest)
    com.google.protobuf.MessageOrBuilder {
}
